### ISSUE TITLE
clear all my passward saved by chrome

### ISSUE THREAD

**Issue by xBoyMinemc** [graynjo/Heimdallr#6]
![image](https://user-images.githubusercontent.com/86919167/210397761-2e1c2e5d-a34f-46f4-9f86-74b58a816551.png)

  
 
did it as well as you want? 
thats too inconvenient.And,I don't sync my passwords to Google Cloud very often

**Comment by xBoyMinemc** [comment]
Don't know why, but I also lost the password data stored in my Google account  
So although the timing is the same, there may be other reasons  
thats all

**Comment by graynjo** [comment]
事实上，持久化数据的清理是包含已保存的密码的。这个已保存的密码是指浏览器的密码管理器中的数据。你可以将鼠标悬停在这个功能的文字部分获取被清除的数据的类型列表。
当浏览器的密码管理器中的数据被清除后，一旦进行google账号的同步，可能会用这个空的密码本代替之前的密码本。
如果这对你造成了不便，我很抱歉。因为在我的使用场景中（web攻击场景），用户会避免在浏览器登录跟本人有关的账号。我会考虑将这个数据在后续版本中是否保存。再次向你表示抱歉。

In fact, the persistent data is cleaned up to include saved passwords. This saved password is the data in the browser's password manager. You can hover over the text section of this feature to get a list of the types of data being purged.
When the data in the browser's password manager is cleared, this empty password book may be used to replace the previous password book once the synchronization of the google account is performed.
I'm sorry if this causes you any inconvenience. Because in my usage scenario (web attack scenario), users will avoid logging into accounts related to me in the browser. I will consider whether to save this data in a subsequent version. Once again, I apologize to you.

![image](https://user-images.githubusercontent.com/49585390/212636526-e0d6d36b-d7c5-4c24-810b-5c6292b40aed.png)

**Comment by graynjo** [comment]
经过考虑，我决定在README中将这个问题强调，但是这个功能可能不会改变。
After some consideration, I decided to highlight this issue in the README documentation, but this feature may not change.
